### PR TITLE
Fix minor issues. Add a group assignment set.

### PR DESCRIPTION
**Pull request by KwangmooKoh**
- Port to Python 3 (and 2).
- Fix some issues in Boolean and Choose.
- Fix unit tests.
- Add a group assignment set (GroupAssign).

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Will this still work with Python 2? I guess it's ok if it doesn't but generally I've been keeping compatibility.

**Comment by KwangmooKoh** [comment]
I think it should be compatible but haven't tested it on Python 2. I
changed the code that is for both 2 and 3 based on:
http://python-future.org/compatible_idioms.html

**Comment by KwangmooKoh** [comment]
Oh, btw, I used the lap package instead of munkres package to solve linear
assignment problem.
https://github.com/gatagat/lap

The solver in munkres package is written in Python, was prohibitively slow
particularly when there are many neighbors to search.
The selection was purely based on the benchmark at
https://github.com/cheind/py-lapsolver. (See the benchmark at the bottom of
the page.)

**Comment by SteveDiamond** [comment]
Ok sounds good!

**Pull request merged**
